version: 2
jobs:
  test:
    docker:
      - image: node:6.11

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install node modules
          command: npm i
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
            - /root/.npm
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - greenlight
                - terminator
                - staging
                - release
